import type { CopyOutput, DesignOutput, SEOOutput } from '@/types'

export function exportToReact(
  copy: CopyOutput,
  design: DesignOutput,
  seo: SEOOutput
): string {
  const dir = design.directions.find((d) => d.id === design.selectedDirectionId)
  if (!dir) throw new Error('No selected design direction')

  const sections = design.sectionOrder
    .map((type) => copy.sections.find((s) => s.sectionType === type))
    .filter(Boolean) as CopyOutput['sections']

  const paletteObj = JSON.stringify(dir.palette, null, 4)
    .split('\n')
    .map((line, i) => (i === 0 ? line : `  ${line}`))
    .join('\n')

  return `// ============================================================
// Generated by PageForge — ${new Date().toISOString().split('T')[0]}
// Product: ${seo.pageTitle}
// ============================================================
// HOW TO USE:
//   1. Copy this file into your Next.js or React project
//   2. Install Google Fonts for: ${dir.typography.heading}, ${dir.typography.body}
//   3. Import and render <LandingPage /> in your page component
// ============================================================

import React from 'react'

const palette = ${paletteObj}

const typography = {
  heading: "'${dir.typography.heading}', system-ui, sans-serif",
  body: "'${dir.typography.body}', system-ui, sans-serif",
}

// ── Section Components ────────────────────────────────────────

${sections.map((s) => renderReactSection(s)).join('\n\n')}

// ── Root Component ────────────────────────────────────────────

export default function LandingPage() {
  return (
    <div style={{ fontFamily: typography.body, backgroundColor: palette.background, color: palette.foreground }}>
      {/* SEO — add these to your <head> via Next.js Metadata API */}
      {/* pageTitle: "${seo.pageTitle}" */}
      {/* metaDescription: "${seo.metaDescription}" */}
      {/* keywords: "${seo.keywords.join(', ')}" */}

${sections.map((s) => `      <${toPascalCase(s.sectionType)}Section />`).join('\n')}
    </div>
  )
}
`
}

function renderReactSection(section: CopyOutput['sections'][0]): string {
  const name = `${toPascalCase(section.sectionType)}Section`

  switch (section.sectionType) {
    case 'hero':
      return `function ${name}() {
  return (
    <section style={{ background: palette.primary, color: palette.primaryForeground, padding: '6rem 1.5rem', textAlign: 'center' }}>
      <div style={{ maxWidth: 800, margin: '0 auto' }}>
        <h1 style={{ fontFamily: typography.heading, fontSize: 'clamp(2rem,5vw,3.5rem)', fontWeight: 700, marginBottom: '1.5rem' }}>
          ${escape(section.headline ?? '')}
        </h1>
        <p style={{ fontSize: '1.25rem', marginBottom: '2rem', opacity: 0.9 }}>
          ${escape(section.subheadline ?? '')}
        </p>
        ${section.body ? `<p style={{ marginBottom: '2rem', opacity: 0.75 }}>${escape(section.body)}</p>` : ''}
        ${section.ctaText ? `<a href="#" style={{ display: 'inline-block', background: palette.accent, color: palette.primaryForeground, padding: '0.875rem 2rem', borderRadius: 8, fontWeight: 600, fontSize: '1.1rem' }}>
          ${escape(section.ctaText)}
        </a>` : ''}
      </div>
    </section>
  )
}`

    case 'logos':
      return `function ${name}() {
  const companies = ['Acme Corp', 'Fieldline', 'Vault Systems', 'Lumio', 'Proxima']
  return (
    <section style={{ background: palette.muted, padding: '3rem 1.5rem', borderTop: \`1px solid \${palette.border}\`, borderBottom: \`1px solid \${palette.border}\` }}>
      <div style={{ maxWidth: 1200, margin: '0 auto', textAlign: 'center' }}>
        <p style={{ color: palette.mutedForeground, marginBottom: '2rem', fontSize: '0.875rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          ${escape(section.headline ?? '')}
        </p>
        <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '3rem', flexWrap: 'wrap', opacity: 0.6 }}>
          {companies.map(name => (
            <span key={name} style={{ fontWeight: 700, fontSize: '1.1rem', color: palette.mutedForeground }}>{name}</span>
          ))}
        </div>
      </div>
    </section>
  )
}`

    case 'problem':
      return `function ${name}() {
  const items = ${JSON.stringify(section.items ?? [], null, 4)}
  return (
    <section style={{ padding: '5rem 1.5rem' }}>
      <div style={{ maxWidth: 1200, margin: '0 auto' }}>
        <div style={{ textAlign: 'center', maxWidth: 700, margin: '0 auto 3rem' }}>
          <h2 style={{ fontFamily: typography.heading, marginBottom: '1rem' }}>${escape(section.headline ?? '')}</h2>
          <p style={{ fontSize: '1.125rem', color: palette.mutedForeground }}>${escape(section.subheadline ?? '')}</p>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(280px,1fr))', gap: '2rem' }}>
          {items.map(item => (
            <div key={item.id} style={{ background: palette.muted, border: \`1px solid \${palette.border}\`, borderRadius: 12, padding: '2rem' }}>
              <h3 style={{ color: palette.primary, marginBottom: '0.75rem' }}>{item.title}</h3>
              <p style={{ color: palette.mutedForeground }}>{item.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}`

    case 'features':
      return `function ${name}() {
  const items = ${JSON.stringify(section.items ?? [], null, 4)}
  return (
    <section style={{ background: palette.muted, padding: '5rem 1.5rem' }}>
      <div style={{ maxWidth: 1200, margin: '0 auto' }}>
        <div style={{ textAlign: 'center', maxWidth: 700, margin: '0 auto 3rem' }}>
          <h2 style={{ fontFamily: typography.heading, marginBottom: '1rem' }}>${escape(section.headline ?? '')}</h2>
          <p style={{ color: palette.mutedForeground }}>${escape(section.subheadline ?? '')}</p>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(280px,1fr))', gap: '2rem' }}>
          {items.map(item => (
            <div key={item.id} style={{ background: palette.background, border: \`1px solid \${palette.border}\`, borderRadius: 12, padding: '2rem' }}>
              <div style={{ width: 48, height: 48, background: palette.primary, borderRadius: 10, marginBottom: '1rem', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <span style={{ color: palette.primaryForeground, fontSize: '1.25rem' }}>◆</span>
              </div>
              <h3 style={{ marginBottom: '0.5rem' }}>{item.title}</h3>
              <p style={{ color: palette.mutedForeground }}>{item.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}`

    case 'testimonials':
      return `function ${name}() {
  const items = ${JSON.stringify(section.items ?? [], null, 4)}
  return (
    <section style={{ padding: '5rem 1.5rem' }}>
      <div style={{ maxWidth: 1200, margin: '0 auto' }}>
        <h2 style={{ fontFamily: typography.heading, textAlign: 'center', marginBottom: '3rem' }}>${escape(section.headline ?? '')}</h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(300px,1fr))', gap: '2rem' }}>
          {items.map(item => (
            <div key={item.id} style={{ background: palette.muted, borderLeft: \`4px solid \${palette.accent}\`, borderRadius: 12, padding: '2rem' }}>
              <p style={{ fontStyle: 'italic', lineHeight: 1.7, marginBottom: '1.5rem' }}>{item.description}</p>
              <p style={{ fontWeight: 600, color: palette.primary, fontSize: '0.9rem' }}>{item.title}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}`

    case 'pricing':
      return `function ${name}() {
  const plans = ${JSON.stringify(section.items ?? [], null, 4)}
  return (
    <section style={{ background: palette.muted, padding: '5rem 1.5rem' }}>
      <div style={{ maxWidth: 1200, margin: '0 auto' }}>
        <div style={{ textAlign: 'center', maxWidth: 600, margin: '0 auto 3rem' }}>
          <h2 style={{ fontFamily: typography.heading, marginBottom: '1rem' }}>${escape(section.headline ?? '')}</h2>
          <p style={{ color: palette.mutedForeground }}>${escape(section.subheadline ?? '')}</p>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(300px,1fr))', gap: '2rem', maxWidth: 800, margin: '0 auto' }}>
          {plans.map((plan, i) => (
            <div key={plan.id} style={{ background: palette.background, border: \`\${i === 1 ? 2 : 1}px solid \${i === 1 ? palette.primary : palette.border}\`, borderRadius: 12, padding: '2rem' }}>
              <h3 style={{ color: palette.primary, marginBottom: '1rem' }}>{plan.title}</h3>
              <p style={{ color: palette.mutedForeground, whiteSpace: 'pre-line' }}>{plan.description}</p>
              <a href="#" style={{ display: 'block', textAlign: 'center', background: i === 1 ? palette.accent : palette.primary, color: palette.primaryForeground, padding: '0.875rem', borderRadius: 8, fontWeight: 600, marginTop: '1.5rem' }}>
                ${escape(section.ctaText ?? 'Get started')}
              </a>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}`

    case 'faq':
      return `function ${name}() {
  const [open, setOpen] = React.useState<string | null>(null)
  const items = ${JSON.stringify(section.items ?? [], null, 4)}
  return (
    <section style={{ padding: '5rem 1.5rem' }}>
      <div style={{ maxWidth: 800, margin: '0 auto' }}>
        <h2 style={{ fontFamily: typography.heading, textAlign: 'center', marginBottom: '3rem' }}>${escape(section.headline ?? '')}</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          {items.map(item => (
            <div key={item.id} style={{ border: \`1px solid \${palette.border}\`, borderRadius: 8, overflow: 'hidden' }}>
              <button onClick={() => setOpen(open === item.id ? null : item.id)}
                style={{ width: '100%', padding: '1.5rem', textAlign: 'left', background: 'none', border: 'none', cursor: 'pointer', fontWeight: 600, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                {item.title}
                <span style={{ color: palette.primary }}>{open === item.id ? '−' : '+'}</span>
              </button>
              {open === item.id && (
                <div style={{ padding: '0 1.5rem 1.5rem', color: palette.mutedForeground, lineHeight: 1.7 }}>
                  {item.description}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}`

    case 'cta':
      return `function ${name}() {
  return (
    <section style={{ background: palette.primary, color: palette.primaryForeground, padding: '5rem 1.5rem', textAlign: 'center' }}>
      <div style={{ maxWidth: 700, margin: '0 auto' }}>
        <h2 style={{ fontFamily: typography.heading, color: palette.primaryForeground, marginBottom: '1rem' }}>
          ${escape(section.headline ?? '')}
        </h2>
        <p style={{ fontSize: '1.125rem', opacity: 0.9, marginBottom: '2rem' }}>
          ${escape(section.subheadline ?? '')}
        </p>
        ${section.ctaText ? `<a href="#" style={{ display: 'inline-block', background: palette.accent, color: palette.primaryForeground, padding: '0.875rem 2rem', borderRadius: 8, fontWeight: 600, fontSize: '1.1rem' }}>
          ${escape(section.ctaText)}
        </a>` : ''}
        ${section.body ? `<p style={{ marginTop: '1.5rem', opacity: 0.7, fontSize: '0.875rem' }}>${escape(section.body)}</p>` : ''}
      </div>
    </section>
  )
}`

    default:
      return `function ${name}() { return null }`
  }
}

function toPascalCase(str: string): string {
  return str
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
}

function escape(str: string): string {
  return str.replace(/'/g, "\\'").replace(/`/g, '\\`').replace(/\$/g, '\\$')
}
